### ISSUE TITLE
Vulnerability Report

### ISSUE THREAD

**Issue by asafbiton** [BadOPCode/NoDash#24]
Hi @BadOPCode, my name is Asaf and I work for Snyk. We have received a vulnerability report which we verified and would like to disclose responsibly. Unfortunately, we could not find contact details for this project. If you could please email me at `asafbit [at] snyk.io` I would be happy to discuss this matter further - Thank you!

**Comment by BadOPCode** [comment]
Sorry for the delay. Will send an email now.
